import {contestsAndActivities} from './data/contestsAndActivities.js';

// The export is generated by this site, not by the old /projects/en route.
// Keep the author-owned portfolio snapshot as the single content source for
// both the map story and PDF. jsPDF, QR generation, and its font are on demand.
const FONT_URL = '/fonts/BatiPortfolioSans-Regular.ttf';
const FONT_FILE = 'BatiPortfolioSans-Regular.ttf';
const FONT_NAME = 'BatiPortfolioSans';
const PUBLIC_SITE = 'https://batikanor.com';
const INLINE_MEDIA = /\{\{(image|embed|gdrive_embed)\[(\d+)\]\}\}/g;
const MARKDOWN_LINK = /\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g;
const PAGE = Object.freeze({margin: 18, top: 23, bottom: 20, line: 4.8});

function isUsableUrl(url) {
  if (typeof url !== 'string') return false;
  try { return ['http:', 'https:'].includes(new URL(url, PUBLIC_SITE).protocol); }
  catch { return false; }
}

export function mediaUrl(media) {
  return typeof media === 'string' ? media : media?.url;
}

export function projectMedia(project) {
  return [
    ...(project.images ?? []).map((item, index) => ({kind: 'image', index, item})),
    ...(project.gdrive_embed ?? []).map((item, index) => ({kind: 'embed', index, item}))
  ];
}

export function markdownLinks(text = '') {
  return [...text.matchAll(MARKDOWN_LINK)].map(match => ({label: match[1], url: match[2]}));
}

export function plainProjectText(text = '') {
  return text
    .replace(MARKDOWN_LINK, '$1')
    .replace(/\*\*|(?<!\*)\*(?!\*)/g, '')
    .replace(/`/g, '')
    .replace(/[ \t]+/g, ' ')
    .trim();
}

/** Preserve the author's inline media order; append all unused media after it. */
export function projectBlocks(project) {
  const blocks = [];
  const used = new Set();
  const description = project.longDescription ?? '';
  let start = 0;
  for (const match of description.matchAll(INLINE_MEDIA)) {
    const preceding = description.slice(start, match.index);
    for (const paragraph of preceding.split(/\n+/)) {
      const text = plainProjectText(paragraph);
      if (text) blocks.push({type: 'paragraph', text});
    }
    const [, rawKind, rawIndex] = match;
    const kind = rawKind === 'image' ? 'image' : 'embed';
    const index = Number(rawIndex);
    const item = kind === 'image' ? project.images?.[index] : project.gdrive_embed?.[index];
    if (item) {
      blocks.push({type: 'media', kind, index, item});
      used.add(`${kind}:${index}`);
    }
    start = match.index + match[0].length;
  }
  for (const paragraph of description.slice(start).split(/\n+/)) {
    const text = plainProjectText(paragraph);
    if (text) blocks.push({type: 'paragraph', text});
  }
  for (const item of projectMedia(project)) {
    if (!used.has(`${item.kind}:${item.index}`)) blocks.push({type: 'media', ...item});
  }
  return blocks;
}

function referenceLinks(project) {
  const all = [
    ...markdownLinks(project.longDescription),
    ...(project.links ?? []),
    ...(project.githubRepo ? [{label: 'GitHub Repository', url: `https://github.com/${project.githubRepo}`}] : [])
  ];
  const seen = new Set();
  return all.filter(({url}) => {
    if (!isUsableUrl(url) || seen.has(url)) return false;
    seen.add(url);
    return true;
  });
}

function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  let result = '';
  for (let offset = 0; offset < bytes.length; offset += 0x8000) {
    result += String.fromCharCode(...bytes.subarray(offset, offset + 0x8000));
  }
  return btoa(result);
}

async function loadFont(pdf, fetcher) {
  const response = await fetcher(FONT_URL);
  if (!response.ok) throw new Error(`Could not load portfolio PDF font (${response.status})`);
  pdf.addFileToVFS(FONT_FILE, arrayBufferToBase64(await response.arrayBuffer()));
  pdf.addFont(FONT_FILE, FONT_NAME, 'normal');
  pdf.setFont(FONT_NAME, 'normal');
}

export function driveThumbnailUrl(url) {
  if (typeof url !== 'string') return null;
  try {
    const parsed = new URL(url);
    if (parsed.hostname !== 'drive.google.com') return null;
    const id = parsed.pathname.match(/^\/file\/d\/([^/]+)/)?.[1];
    // The Drive /thumbnail endpoint redirects to this image CDN but the
    // redirect response itself lacks CORS. Fetch the public CDN URL directly.
    return id ? `https://lh3.googleusercontent.com/d/${encodeURIComponent(id)}=w1200` : null;
  } catch { return null; }
}

async function imageData(media, fetcher, {compressPdf, compressionStrength, imageScale}) {
  const url = mediaUrl(media);
  const local = url?.startsWith('/') && /\.(?:jpe?g|png|webp)(?:\?|$)/i.test(url);
  // Google's public thumbnail CDN allows browser CORS. The old weserv image
  // proxy used by production now often 403s.
  // Media can also be video or inaccessible; all originals remain linked.
  const source = local ? url : driveThumbnailUrl(url);
  if (!source) return null;
  const controller = typeof AbortController !== 'undefined' ? new AbortController() : null;
  const timer = controller ? setTimeout(() => controller.abort(), 6500) : null;
  try {
    const response = await fetcher(source, controller ? {signal: controller.signal} : undefined);
    if (!response.ok) return null;
    if (!response.headers.get('content-type')?.startsWith('image/')) return null;
    const blob = await response.blob();
    const objectUrl = URL.createObjectURL(blob);
    try {
      const image = new Image();
      image.src = objectUrl;
      await image.decode();
      const canvas = document.createElement('canvas');
      const scale = Math.min(1, 1200 / Math.max(image.naturalWidth, image.naturalHeight)) * imageScale;
      canvas.width = Math.max(1, Math.round(image.naturalWidth * scale));
      canvas.height = Math.max(1, Math.round(image.naturalHeight * scale));
      canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height);
      return {data: canvas.toDataURL('image/jpeg', compressPdf ? 1 - compressionStrength : 1), ratio: canvas.width / canvas.height};
    } finally { URL.revokeObjectURL(objectUrl); }
  } catch { return null; }
  finally { if (timer) clearTimeout(timer); }
}

// The PDF renderer is mostly synchronous. Let the progress message paint
// occasionally instead of monopolising the same main thread as the 3D map.
// MessageChannel still yields promptly in a background tab where rAF pauses.
function yieldToBrowser() {
  if (typeof document !== 'undefined' && !document.hidden && typeof requestAnimationFrame === 'function') {
    return new Promise(resolve => requestAnimationFrame(() => resolve()));
  }
  if (typeof MessageChannel !== 'undefined') {
    return new Promise(resolve => {
      const channel = new MessageChannel();
      channel.port1.onmessage = () => {
        channel.port1.close();
        channel.port2.close();
        resolve();
      };
      channel.port2.postMessage(0);
    });
  }
  return Promise.resolve();
}

function writeDocument(pdf, projects, {includeImages, compressPdf, compressionStrength, imageScale, onProgress, fetcher, QRCode}) {
  const width = pdf.internal.pageSize.getWidth();
  const height = pdf.internal.pageSize.getHeight();
  const right = width - PAGE.margin;
  const contentWidth = width - 2 * PAGE.margin;
  let y = PAGE.top;
  let pageNumber = 1;
  const destinations = [];
  const qrCache = new Map();

  async function qrImage(url) {
    if (!QRCode || typeof document === 'undefined') return null;
    if (qrCache.has(url)) return qrCache.get(url);
    try {
      const image = await QRCode.toDataURL(url, {width: 140, margin: 1, errorCorrectionLevel: 'M'});
      qrCache.set(url, image);
      return image;
    } catch { return null; }
  }

  function footer() {
    pdf.setTextColor(115, 126, 137);
    pdf.setFontSize(8);
    pdf.text('Batıkan Bora Ormancı · Projects & Achievements', PAGE.margin, height - 9);
    pdf.text(String(pageNumber), right, height - 9, {align: 'right'});
  }
  function nextPage() { footer(); pdf.addPage(); pageNumber += 1; y = PAGE.top; }
  function space(amount) { if (y + amount > height - PAGE.bottom) nextPage(); }
  function textLines(text, size, lineHeight = PAGE.line, color = [33, 41, 49], gap = 0) {
    pdf.setFontSize(size);
    pdf.setTextColor(...color);
    const lines = pdf.splitTextToSize(String(text), contentWidth);
    for (const line of lines) { space(lineHeight); pdf.text(line, PAGE.margin, y); y += lineHeight; }
    y += gap;
  }
  function link(label, url) {
    const safe = isUsableUrl(url) ? new URL(url, PUBLIC_SITE).href : null;
    if (!safe) return;
    pdf.setTextColor(47, 91, 147);
    pdf.setFontSize(8.5);
    const lines = pdf.splitTextToSize(`${label} · ${safe}`, contentWidth);
    for (const line of lines) {
      space(PAGE.line);
      pdf.textWithLink(line, PAGE.margin, y, {url: safe});
      y += PAGE.line;
    }
    y += 1.5;
  }
  async function media(item, kind, index) {
    const url = mediaUrl(item);
    const caption = typeof item === 'string' ? `${kind === 'image' ? 'Image' : 'Media'} ${index + 1}` :
      item.abovePhotoCaption || `${kind === 'image' ? 'Image' : 'Media'} ${index + 1}`;
    textLines(caption, 9, PAGE.line, [126, 78, 35], 1);
    if (item?.credit) textLines(`Credit: ${item.credit}`, 8, PAGE.line, [103, 112, 119], 1);
    if (url) {
      const safe = isUsableUrl(url) ? new URL(url, PUBLIC_SITE).href : null;
      const qr = safe ? await qrImage(safe) : null;
      if (qr) {
        space(14);
        pdf.setDrawColor(222, 227, 228);
        pdf.setFillColor(248, 249, 248);
        pdf.rect(PAGE.margin, y, contentWidth, 12, 'FD');
        pdf.addImage(qr, 'PNG', PAGE.margin + 1, y + 1, 10, 10);
        pdf.setTextColor(47, 91, 147);
        pdf.setFontSize(8.5);
        pdf.textWithLink('Open original media', PAGE.margin + 15, y + 7.5, {url: safe});
        pdf.link(PAGE.margin, y, contentWidth, 12, {url: safe});
        y += 15;
      } else link('Open original media', url);
    }
    if (!includeImages) return;
    // Public Drive thumbnails are best-effort visual previews, never a
    // replacement for the original full-resolution media link above.
    const image = await imageData(item, fetcher, {compressPdf, compressionStrength, imageScale});
    if (!image) return;
    const imageWidth = Math.min(contentWidth, 118) * imageScale;
    const imageHeight = Math.min(90, imageWidth / image.ratio);
    space(imageHeight + 3);
    pdf.addImage(image.data, 'JPEG', PAGE.margin, y, imageWidth, imageHeight);
    y += imageHeight + 4;
  }

  return (async () => {
    // Plan as many TOC pages as the original titles need, then reserve them
    // before content so every link can point to the actual target page.
    const tocPages = [[]];
    let tocY = 42;
    pdf.setFontSize(9.6);
    projects.forEach((project, index) => {
      const lines = pdf.splitTextToSize(`${String(index + 1).padStart(2, '0')}  ${project.title}`, contentWidth - 26);
      const rowHeight = Math.max(12, lines.length * 5 + 6);
      if (tocY + rowHeight > height - PAGE.bottom - 3) { tocPages.push([]); tocY = 42; }
      tocPages.at(-1).push({index, lines, y: tocY, rowHeight});
      tocY += rowHeight;
    });

    // Cover is intentionally factual; it carries no invented project titles.
    pdf.setFillColor(16, 36, 41);
    pdf.rect(0, 0, width, 22, 'F');
    pdf.setTextColor(245, 220, 181);
    pdf.setFontSize(9);
    pdf.text('BATIKAN  /  HACKER · DEVELOPER · ENTREPRENEUR', PAGE.margin, 14);
    pdf.setTextColor(34, 41, 47);
    pdf.setFontSize(25);
    pdf.text('Batıkan Bora Ormancı', PAGE.margin, 55);
    pdf.setFontSize(19);
    pdf.text('Summary of achievements', PAGE.margin, 69);
    pdf.setFontSize(10);
    pdf.setTextColor(104, 111, 119);
    pdf.text(`${projects.length} entries · Original descriptions, media and references`, PAGE.margin, 82);
    pdf.text(`Downloaded ${new Date().toLocaleDateString()}`, PAGE.margin, 90);
    pdf.setDrawColor(227, 205, 170);
    pdf.line(PAGE.margin, 100, right, 100);
    pdf.setFontSize(10);
    pdf.setTextColor(47, 91, 147);
    pdf.textWithLink('Explore the interactive achievement map', PAGE.margin, 113, {url: PUBLIC_SITE});
    pdf.setTextColor(85, 95, 101);
    pdf.setFontSize(9);
    pdf.text('This report is based on the same author-written project content as the site.', PAGE.margin, 123);
    pdf.text('Professional work experience is detailed separately in the CV.', PAGE.margin, 130);
    for (let i = 0; i < tocPages.length; i++) nextPage();
    nextPage();

    for (let i = 0; i < projects.length; i++) {
      const project = projects[i];
      onProgress?.({index: i, total: projects.length, title: project.title});
      if (i < 4 || i % 4 === 0) await yieldToBrowser();
      const mapData = project.mapData ?? {};
      const title = `${String(i + 1).padStart(2, '0')} / ${projects.length}  ${project.title}`;
      pdf.setFontSize(14);
      const titleLines = pdf.splitTextToSize(title, contentWidth - 31);
      const headerHeight = Math.max(27, titleLines.length * 7.1 + 8);
      space(headerHeight + 9);
      destinations.push({page: pageNumber, top: y});
      // Hash links work on the current production site and remain supported by
      // the replacement map; localhost URLs must never leak into shared PDFs.
      const mapUrl = `${PUBLIC_SITE}/#${encodeURIComponent(project.slug)}`;
      pdf.setFillColor(249, 248, 245);
      pdf.setDrawColor(218, 220, 216);
      pdf.rect(PAGE.margin, y, contentWidth, headerHeight, 'FD');
      pdf.setFillColor(211, 142, 77);
      pdf.rect(PAGE.margin, y, 1.7, headerHeight, 'F');
      pdf.setTextColor(139, 82, 38);
      titleLines.forEach((line, lineIndex) => pdf.text(line, PAGE.margin + 5, y + 9 + lineIndex * 7.1));
      const headerQr = await qrImage(mapUrl);
      if (headerQr) pdf.addImage(headerQr, 'PNG', right - 21, y + 3, 19, 19);
      pdf.link(PAGE.margin, y, contentWidth, headerHeight, {url: mapUrl});
      y += headerHeight + 6;
      const location = [mapData.venue, mapData.city, mapData.country].filter(Boolean).join(' · ');
      textLines([project.date, location].filter(Boolean).join('  |  '), 9, 4.9, [103, 112, 119], 3);
      link('Open this achievement on the map', mapUrl);
      if (project.shortDescription) textLines(project.shortDescription, 10, 5.2, [45, 54, 61], 3);
      if (project.categories?.length) textLines(`Categories: ${project.categories.join(', ')}`, 8.5, 4.8, [95, 102, 109], 1);
      for (const block of projectBlocks(project)) {
        if (block.type === 'paragraph') textLines(block.text, 9.3, 5.0, [35, 41, 46], 2.5);
        else await media(block.item, block.kind, block.index);
      }
      if (project.technologies?.length) {
        textLines(`Technologies: ${project.technologies.join(' · ')}`, 8.5, 4.8, [95, 102, 109], 3);
      }
      const links = referenceLinks(project);
      if (links.length) {
        textLines('Original references', 10, 5.2, [126, 78, 35], 1);
        for (const item of links) link(item.label, item.url);
      }
      y += 8;
    }
    onProgress?.({index: projects.length, total: projects.length, title: 'Complete'});
    await yieldToBrowser();
    footer();
    const finalPage = pageNumber;
    tocPages.forEach((rows, tocIndex) => {
      pdf.setPage(tocIndex + 2);
      pdf.setTextColor(34, 41, 47);
      pdf.setFontSize(18);
      pdf.text('Table of contents', PAGE.margin, 29);
      pdf.setTextColor(108, 119, 124);
      pdf.setFontSize(8.5);
      pdf.text(`${tocIndex + 1} / ${tocPages.length} · Select a title to jump to its achievement`, PAGE.margin, 36);
      rows.forEach(({index, lines, y: rowY, rowHeight}) => {
        const project = projects[index];
        const destination = destinations[index];
        pdf.setDrawColor(228, 231, 229);
        pdf.line(PAGE.margin, rowY + rowHeight - 2, right, rowY + rowHeight - 2);
        pdf.setFontSize(9.6);
        pdf.setTextColor(41, 57, 60);
        lines.forEach((line, lineIndex) => pdf.text(line, PAGE.margin, rowY + lineIndex * 5));
        pdf.setFontSize(8);
        pdf.setTextColor(130, 91, 49);
        pdf.text(String(destination.page), right, rowY, {align: 'right'});
        const place = [project.date, project.mapData?.city].filter(Boolean).join(' · ');
        pdf.setFontSize(7.8);
        pdf.setTextColor(109, 118, 119);
        pdf.text(place, PAGE.margin + 6, rowY + lines.length * 5);
        pdf.link(PAGE.margin, rowY - 4, contentWidth, rowHeight, {pageNumber: destination.page});
      });
    });
    pdf.setPage(finalPage);
    return pdf;
  })();
}

/** Build and download the same 32 authored projects without leaving Earth. */
export async function exportProjectsPdf({
  projects = contestsAndActivities,
  includeImages = true,
  imageScale = 1,
  compressPdf = true,
  compressionStrength = 0.1,
  fileName,
  onProgress,
  fetcher = fetch,
  save = true
} = {}) {
  if (!Array.isArray(projects) || !projects.length) throw new Error('No projects to export');
  if (!Number.isFinite(imageScale) || imageScale < 0.2 || imageScale > 1) throw new RangeError('Image scale must be between 0.2 and 1');
  if (!Number.isFinite(compressionStrength) || compressionStrength < 0.1 || compressionStrength > 0.9) throw new RangeError('Compression strength must be between 0.1 and 0.9');
  const {jsPDF} = await import('jspdf');
  const QRCode = (await import('qrcode')).default;
  const pdf = new jsPDF({format: 'a4', unit: 'mm', compress: compressPdf});
  await loadFont(pdf, fetcher);
  await writeDocument(pdf, projects, {includeImages, compressPdf, compressionStrength, imageScale, onProgress, fetcher, QRCode});
  const resolvedName = fileName || (compressPdf ? 'batikan-achievements-summary-compressed.pdf' : includeImages ? 'batikan-achievements-summary-with-images.pdf' : 'batikan-achievements-summary.pdf');
  if (save) pdf.save(resolvedName);
  return pdf;
}
